# Generated by Django 5.0.2 on 2024-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vuelo",
            fields=[
                ("id_vuelo", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
