# Generated by Django 5.0.2 on 2024-03-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_vuelo_delete_comment_delete_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vuelo",
            name="tipo",
            field=models.CharField(
                choices=[("nacional", "Nacional"), ("internacional", "Internacional")],
                max_length=255,
            ),
        ),
    ]
