# Generated by Django 5.0.2 on 2024-03-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_alter_vuelo_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vuelo",
            name="tipo",
            field=models.CharField(max_length=100),
        ),
    ]
